# Generated by Django 2.1.7 on 2019-04-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20190427_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadapp.File'),
        ),
    ]
