# Generated by Django 2.1.7 on 2019-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.CharField(max_length=256, null='No Caption'),
            preserve_default='No Caption',
        ),
    ]
